apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - ap-south-1a
                - ap-south-1b
      containers:
      - name: frontend
        image: 878436876448.dkr.ecr.ap-south-1.amazonaws.com/chatapp-frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: chatapp-config
        - secretRef:
            name: chatapp-secrets
        env:
        - name: BACKEND_HOST
          value: backend